#!/bin/bash
#
#This script try to run everything
#
#

#make the directory if not exist, and create new log files
mkdir -p data
mkdir -p features
# Clean the data and feature directories!
rm -f data/*
rm -f data/*
echo '' > data/program.log
echo '' > data/error.log
echo '' > data/matlab.log

python preprocessor.py >> data/program.log 2>>data/error.log
python genLMFeature.py >> data/program.log 2>>data/error.log 

matlab -nodesktop -nosplash -r "run('classify');exit" >> data/matlab.log 2>>data/error.log

cat data/result
